### ISSUE TITLE
naming violations

### ISSUE THREAD

**Issue by danmarsden** [Human-Logic-Software-LLC/Levitate#10]
https://github.com/Human-Logic-Software-LLC/mdl_levitate/blob/main/lib.php#L31

Please see:
https://moodledev.io/general/development/policies/codingstyle/frankenstyle#function-names

note this is a blocker for plugins db approval

**Comment by sreenivasmalae** [comment]
All function names have been adjusted to adhere to the 'frankenstyle'.
