### ISSUE TITLE
please do not mix inline php code with classes

### ISSUE THREAD

**Issue by danmarsden** [Human-Logic-Software-LLC/Levitate#11]
https://github.com/Human-Logic-Software-LLC/mdl_levitate/blob/main/selected_courses.php#L47

that class should be in it's own file, and should also be careful to follow the class naming rules:
https://moodledev.io/general/development/policies/codingstyle/frankenstyle#class-names

**Comment by sreenivasmalae** [comment]
The class has been relocated and renamed to 'frankenstyle' in compliance with the class naming rules.

**Comment by raortegar** [comment]
Hi @sreenivasmalae, 
Thanks for relocate the class. Could you close this issue please. 
Thanks.

**Comment by raortegar** [comment]
We found in file local/levitate/lib.php 
`class local_levitate_form extends moodleform {`

This class should be in a new file like in the following example: https://moodledev.io/docs/apis/subsystems/form
So please locate the local_levitate_form class inside "/classes/form/local_levitate_form.php"
Thanks :)

**Comment by sreenivasmalae** [comment]
Hi @raortegar,

As per the moodle standards (https://moodledev.io/docs/apis/subsystems/form) we have created a new file for the form under the classes folder.

**Comment by raortegar** [comment]
Hi @sreenivasmalae, 
Thanks a lot for it :)
