### ISSUE TITLE
Please don't call curl_init directly

### ISSUE THREAD

**Issue by danmarsden** [Human-Logic-Software-LLC/Levitate#12]
Please don't initate curl_init() directly but use Moodle's own "curl" class which is a wrapper on PHP's curl functions.

This isn't documented well, but if you search the moodle code base for "curl" you should see some good examples.

Moodle has a number of security and proxy settings that need to be respected which this core class takes care of for you.

**Comment by sreenivasmalae** [comment]
Instead of directly initiating curl_init(), we have incorporated Moodle's own 'curl' class.
