### ISSUE TITLE
please use get_config() api instead of db calls to config_plugins table

### ISSUE THREAD

**Issue by danmarsden** [Human-Logic-Software-LLC/Levitate#13]
https://github.com/Human-Logic-Software-LLC/mdl_levitate/blob/main/explore.php#L29

Please use the get_config() api's instead as this is cached/better for general performance.

**Comment by danmarsden** [comment]
similar here:
https://github.com/Human-Logic-Software-LLC/mdl_levitate/blob/main/classes/task/create_course.php#L52

**Comment by sreenivasmalae** [comment]
We've updated the code to utilize the get_config() APIs for improved performance and caching.

**Comment by raortegar** [comment]
Hi @sreenivasmalae , 
Just a suggestion, instead fetch the object you could use something like this: 
`$tokenid = get_config('local_levitate', 'secret');`

Also I don't see where it is used $tokenid in [create_course.php](https://github.com/Human-Logic-Software-LLC/moodle-local_levitate/blob/72f6d7b55d4786c10cfb48d2a228bcfa4d702301/classes/task/create_course.php#L53C10-L53C17) file

**Comment by sreenivasmalae** [comment]
Hi @raortegar 

We have updated the code as per your suggestion.
