### ISSUE TITLE
Missing capability checks

### ISSUE THREAD

**Issue by danmarsden** [Human-Logic-Software-LLC/Levitate#14]
I can see require_login calls - but I can't see anywhere that checks "should this user be allowed to XXX" - eg - should this user be allowed to create a course/view the catalogue/ add a scorm package to this course etc etc.

This is a blocker for plugins db approval.

**Comment by sreenivasmalae** [comment]
In the latest version of the plugin, two distinctive capabilities have been developed: one for exploring courses and the other for analytics.
