### ISSUE TITLE
Incorrect location for settings 

### ISSUE THREAD

**Issue by raortegar** [Human-Logic-Software-LLC/Levitate#18]
Hi, 
In the file settings.php, the setting names are supposed to be plugintype_pluginname/settingname (note the slash) and not plugintype_pluginname_settingname or even just settingname.
I am getting some errors related to this, See: 
```
Duplicate admin page name: analytics
line 960 of /lib/adminlib.php: call to debugging()
line 34 of /local/levitate/settings.php: call to admin_category->add()

Duplicate admin page name: explorecourses
line 960 of /lib/adminlib.php: call to debugging()
line 41 of /local/levitate/settings.php: call to admin_category->add()
```

If you access to Plugins / Local plugins / Levitate / Explore catalog
It redirects you to Local plugins / Levitate / Get token

If you access to Local plugins / Levitate / Analytics 
It throws an error 

In this link you could find an example https://moodledev.io/docs/apis/subsystems/admin#settings-file-example

Cheers.

**Comment by sreenivasmalae** [comment]
Hi @raortegar
 
We've thoroughly reviewed the settings.php file and have ensured that the setting names follow the correct format as per the Moodle documentation (https://moodledev.io/docs/apis/subsystems/admin#settings-file-example).

To resolve the issues you've reported, we recommend updating the plugin from our GitHub repository.

If, after updating, you still encounter the mentioned errors, could you please provide us with detailed steps to reproduce the issue? This information will greatly help us find and fix the problem more easily.

**Comment by raortegar** [comment]
Hi @sreenivasmalae , 
Thanks a lot for fixing the issue. Seems good now, I've tested it and there are no errors anymore. 
I am closing the issue :) Thanks
