### ISSUE TITLE
Missing strings

### ISSUE THREAD

**Issue by raortegar** [Human-Logic-Software-LLC/Levitate#19]
Some strings are missing and the plugin throw some errors and warnings: 

Invalid get_string() identifier: 'levitate:view_levitate_analytics' or component 'local_levitate'. Perhaps you are missing $string['levitate:view_levitate_analytics'] =  ....

Invalid get_string() identifier: 'levitate:view_levitate_catalog' or component 'local_levitate'. Perhaps you are missing $string['levitate:view_levitate_catalog'] = ''; in /var/www/html/moodles/cips_main/moodle/local/levitate/lang/en/local_levitate.php?

Could you have a look at it please? 
Thanks

**Comment by sreenivasmalae** [comment]
Hi @raortegar 

We have updated the language files with the mentioned strings.
