### ISSUE TITLE
Camel case in strings and spelling mistake found

### ISSUE THREAD

**Issue by raortegar** [Human-Logic-Software-LLC/Levitate#26]
**Camel Case:**
Moodle uses sentence case - please check your lang strings as some use camel case.

Please change: 
`$string['coursecategory_required'] = 'Kindly Select the Course Category';
$string['levitate:view_levitate_analytics'] = 'Capability to view Analytics';
$string['levitate:view_levitate_catalog'] = 'Capability to explore Course Catalog';`

To: 
`$string['coursecategory_required'] = 'Kindly select the course category';
 $string['levitate:view_levitate_analytics'] = 'Capability to view analytics';
$string['levitate:view_levitate_catalog'] = 'Capability to explore course catalog';`

**Spelling mistakes:** 

Please change: 
`$string['invalidtoken'] = 'Provided token is not a valid one, Kindly update the token from the plugin setttings';`

To: 
`$string['invalidtoken'] = 'Provided token is not a valid one, Kindly update the token from the plugin settings';`

**Note**: this is not a blocker for approval in the plugins db.

**Comment by sreenivasmalae** [comment]
All the strings are updated as per the guidelines
