### ISSUE TITLE
very fragile undocumented use of external libraries.

### ISSUE THREAD

**Issue by danmarsden** [Human-Logic-Software-LLC/Levitate#27]
@raortegar noticed these and pinged me to ask about my thoughts...
https://github.com/Human-Logic-Software-LLC/moodle-local_levitate/blob/main/analytics.php#L43C38-L43C43

https://github.com/Human-Logic-Software-LLC/moodle-local_levitate/blob/main/css/styles.css#L6

Loading fonts directly from Google will prevent some sites being able to use your plugin and it's not a blocker for approval but it's worth you re-thinking that.

But what concerns me more is that you seem to load the external datatables javascript from the human-logic's own Moodle site which is both a potential privacy and a potential security risk.

You shouldn't really be doing that - sites that implement a CSP policy will likely block it from loading (and they should) - the users of Levitate shouldn't need to "trust" the datatables js hosted on your site. you should really be including the datatables directly in this plugin itself or using a better way to pull that into the plugin that doesn't require an external link to a 3rd party website like this..

If you document that this the plugin does this in your plugins db entry (and your readme) we wouldn't block approval, but rather than documenting it, it would be better to stop doing it this way and just include the datatables js within the plugin code itself.

**Comment by sreenivasmalae** [comment]
Hi @danmarsden @raorteg

Thank you for bringing these concerns to my attention. I've addressed them immediately by removing all external links and storing the necessary JS files locally under the "js" folder. Additionally, I've downloaded the required fonts and stored them in the "fonts" folder within the plugin directory.
