### ISSUE TITLE
missing thirdpartylibs.xml file

### ISSUE THREAD

**Issue by danmarsden** [Human-Logic-Software-LLC/Levitate#29]
now that you've addressed #27 - bringing those 3rd party compoenents into the plugin itself, you need to drop in a thirdpartylibs.xml file that describes these files (and their respective licenses.)

When including an external library in your plugin, you must include a thirdpartylibs.xml file that includes the name, location and license of the library.
More information on this is here:
https://moodledev.io/docs/apis/commonfiles#thirdpartylibsxml
And here:
https://moodledev.io/general/community/plugincontribution/thirdpartylibraries

One of the other advantages of using this is that Moodle's codechecker automatically ignores any files included in the location specificed in the thirdpartylibs.xml file.

Please note - this is typically a blocker for approval in the plugins db.

**Comment by danmarsden** [comment]
note - d3 license is ISC which states:

Copyright 2010-2023 Mike Bostock

Permission to use, copy, modify, and/or distribute this software for any purpose
with or without fee is hereby granted, provided that the above copyright notice
and this permission notice appear in all copies.


I can see the copyright in there on your js file, but it's missing the permission notice - one way to fix this would be to put d3 into it's own folder within your js dir and drop the LICENSE file in at the same time but there are probably other options too.

**Comment by sreenivasmalae** [comment]
Hi @danmarsden 

we have created the thirdpartylibs.xml file and updated the file with required libraries.

Also created a new folder for d3 as mentioned along with its licence file

**Comment by raortegar** [comment]
Hi @sreenivasmalae 
Thanks a lot for working on this! 
Checking the license I see some differences between the file from here https://github.com/d3/d3/releases/tag/v4.13.0 and this one https://github.com/Human-Logic-Software-LLC/moodle-local_levitate/blob/main/js/d3/LICENSE.txt
Could you update the file? 
Also it would be helpful if you could include the path to the repository [here](https://github.com/Human-Logic-Software-LLC/moodle-local_levitate/blob/main/thirdpartylibs.xml#L19)

I guess it should be 
`<repository>https://github.com/d3/d3/releases/tag/v4.13.0</repository>`

Thanks!

**Comment by sreenivasmalae** [comment]
Hi @raortegar 

I've updated the https://github.com/Human-Logic-Software-LLC/moodle-local_levitate/blob/main/js/d3/LICENSE.txt file with the appropriate version. Additionally, I've included the repository tag under d3 in thirdpartylibs.xml, specifying the path to the repository.

Thanks.

**Comment by raortegar** [comment]
Hi @sreenivasmalae 
Thanks a lot for it, looks good now :)
