### ISSUE TITLE
Missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [Human-Logic-Software-LLC/Levitate#7]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin stores user data in a number of tables which will need to be included in the privacy api classes.

More information on the privacy class is here:
https://moodledev.io/docs/apis/subsystems/privacy# 

Your plugin also integrates with an external API and this must also be covered in your privacy api as per:
https://moodledev.io/docs/apis/subsystems/privacy#indicating-that-you-export-data-to-an-external-location

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

**Comment by sreenivasmalae** [comment]
As the plugin doesn't store any user information, the Privacy API has been updated in accordance with the instructions provided in the following URL: https://moodledev.io/docs/apis/subsystems/privacy#

**Comment by danmarsden** [comment]
Use of the null provider class is incorrect. Your tables include a user ID field and moodles core privacy api unit tests will see this and throw an error as the table is not covered by the api.

You also need to be clear what user data is sent to the external api - for example does an end user's email or username get passed to the external end point?

**Comment by sreenivasmalae** [comment]
We removed the user ID from the table. Just to clarify, the user ID in the table is only for reference and doesn't affect how the plugin works.

**Comment by danmarsden** [comment]
cool that should sort it! - thanks! :-)

**Comment by sreenivasmalae** [comment]
The plugin does not export any user information and the null provider class (\core_privacy\local\metadata\null_provider ) is updated. 

Closing the issue.

Thanks
