### ISSUE TITLE
styles.css not specific enough.

### ISSUE THREAD

**Issue by danmarsden** [Human-Logic-Software-LLC/Levitate#9]
in your styles.css you define a number of generic styles that could clash with core moodle code or other locations where simliar names are used. 

Moodle helpfully adds a number of classes to the body tag based on the path that you can use such as:
eg if you are have a file in mod/assign you would see the following class added to the body tag
path-mod-assign
so if you have an item with the class "filething" on the page you would target it like:
```
.path-mod-assign .filething {
   color: red;
}
```

Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code.

**Comment by sreenivasmalae** [comment]
"In the styles.css file, potential clashes with generic styles have been addressed by incorporating specific classes based on the page path. the CSS now includes '.path-local-levitate' to prevent conflicts.

**Comment by danmarsden** [comment]
doesn't look like you've done this everywhere yet?
eg:
https://github.com/Human-Logic-Software-LLC/moodle-local_levitate/blob/main/styles.css#L333-L339

(I didn't look further in your styles.css file - just stopped when I saw that...) - you should check it all yourself again :-)

**Comment by sreenivasmalae** [comment]
I've rechecked the styles.css file and ensured that all the CSS code has been updated to the latest version.
